version: "3.9"
services:
  static-files:
    # nginx config
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.static-files-insecure.compress=true"
      - "traefik.http.routers.static-files-insecure.rule=Host(`localhost`) && PathPrefix(`/static`)"
      - "traefik.http.routers.static-files-insecure.entrypoints=web"
    depends_on:
      - traefik

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile_dev
    command: bash -c "
      gunicorn frontend.main:app -w 2 -b 0.0.0.0:8001 --reload --reload-extra-file /frontend/templates
      "
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./api/.env.development
    depends_on:
      - traefik
      - static-files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-insecure.rule=Host(`localhost`) && PathPrefix(`/frontend`)"
      - "traefik.http.routers.frontend-insecure.entrypoints=web"
      - "traefik.http.middlewares.frontend-sp.stripprefix.prefixes=/frontend"
      - "traefik.http.middlewares.frontend-sp.stripprefix.forceSlash=false"
      - "traefik.http.routers.frontend-insecure.middlewares=frontend-sp"

    restart: on-failure

  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile_dev
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      alembic -c /api/alembic.ini upgrade head;
      uvicorn api.main:app
      --workers 2
      --host 0.0.0.0
      --reload --root-path /api/v1
      "
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
      - traefik
    env_file:
      - ./api/.env.development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`host.docker.internal`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=api-sp"
      - "traefik.http.middlewares.api-sp.stripprefix.prefixes=/api/v1"
      - "traefik.http.middlewares.api-sp.stripprefix.forceSlash=false"
      - "traefik.http.routers.apilh.rule=Host(`localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.apilh.entrypoints=web"
      - "traefik.http.routers.apilh.middlewares=api-sp"

    restart: on-failure

  traefik:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    env_file:
      - ./api/.env.development
    image: postgis/postgis
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - TZ=America/Denver
      - PGTZ=America/Denver
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/.env.development
    environment:
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  postgis-data:

