#
FROM python:3.7-alpine


RUN apk update
RUN apk add build-base
RUN #apt-get install libsqlite3-mod-spatialite -y
RUN apk add unixodbc-dev
RUN apk add freetds-dev
RUN apk add postgresql-dev python3-dev musl-dev
RUN apk add proj-dev
COPY ./celery_requirements.txt /api/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip3 install --no-cache-dir --upgrade -r /api/celery_requirements.txt

#
COPY . /api/