#
FROM python:3.9

#

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update
RUN #apt install libsqlite3-mod-spatialite -y
RUN apt install unixodbc-dev -y
RUN apt install freetds-dev -y
COPY ./requirements.txt /api/

#
RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

#
COPY . /api/