#
FROM python:3.9


RUN apt update
RUN #apk add build-base
RUN #apt-get install libsqlite3-mod-spatialite -y
RUN apt add unixodbc-dev
RUN apt add freetds-dev
RUN apt add postgresql-dev python3-dev musl-dev
RUN apt add proj-dev proj
COPY ./celery_requirements.txt /api/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip3 install --no-cache-dir --upgrade -r /api/celery_requirements.txt

#
COPY . /api/